export interface IndividualService {
  slug: string;
  title: string;
  category: string;
  color: string;
  shortDesc: string;
  longDesc: string;
  tagline: string;
  aboutUs: string;
  benefits: string[];
  keywords: string[];
  relatedSlugs: string[];
}

export const INDIVIDUAL_SERVICES: IndividualService[] = [
  // ─── Web Design & Development ─────────────────────────────────────
  {
    slug: "best-corporate-website-in-vijayawada",
    title: "Corporate Website",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Professional corporate websites that establish credibility and drive business growth.",
    longDesc: "We design and develop corporate websites that communicate authority, build trust, and convert visitors into business leads. Every corporate site we build is structured around your business goals — from investor relations and team profiles to service showcases and contact flows. Clean code, fast loading, and optimised for search from day one.",
    tagline: "Your Business Deserves a Website That Commands Respect — We Build Exactly That",
    aboutUs: "Creators Touch Global has built corporate websites for hospitals, law firms, consulting agencies, and multi-location businesses since 2008. We understand that a corporate website is often the first impression — and we make sure it's the right one. Our sites are designed to reflect your brand's authority while making it effortless for visitors to take the next step.",
    benefits: [
      "Custom corporate design reflecting your brand identity and values",
      "Professional team and leadership profile pages",
      "Service and capability showcases with clear CTAs",
      "Investor relations and media sections where needed",
      "Mobile-responsive design that works across every device",
      "SEO-ready architecture with clean, semantic code",
    ],
    keywords: ["corporate website design", "business website", "professional website", "corporate web development", "company website"],
    relatedSlugs: ["meditron-cdc", "st-pauls-school", "change-ngo"],
  },
  {
    slug: "best-e-commerce-website-in-vijayawada",
    title: "E-Commerce Website",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Online stores that look premium and sell like a machine — day and night.",
    longDesc: "From product catalogues to checkout flows, payment gateways to inventory management — we build e-commerce websites on Shopify and WooCommerce that make buying simple, fast, and trustworthy. Every store is designed to reduce friction, increase average order value, and keep customers coming back.",
    tagline: "Stores That Sell While You Sleep — E-Commerce Built for Real Revenue",
    aboutUs: "We have built online stores for jewellery houses, aesthetics clinics selling skincare, and retail brands going digital for the first time. From Anjaneya Jewellery's heritage catalogue to modern Shopify stores for UK clinics — our e-commerce sites are built to convert, not just display.",
    benefits: [
      "Shopify and WooCommerce store design and development",
      "Product catalogue with filtering, search, and sorting",
      "Secure checkout with UPI, cards, and COD integration",
      "Inventory management with low-stock alerts",
      "Order tracking and shipping integration",
      "Mobile-first design optimised for thumb-friendly shopping",
    ],
    keywords: ["ecommerce website", "online store", "Shopify store", "WooCommerce", "ecommerce development"],
    relatedSlugs: ["threadlift", "fillers-skin"],
  },
  {
    slug: "best-landing-page-design-in-vijayawada",
    title: "Landing Page Design",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "High-converting landing pages that turn ad traffic into paying customers.",
    longDesc: "A landing page has one job — convert. We design focused, distraction-free landing pages that capture leads from your Google Ads, Facebook campaigns, and email marketing. Every element — headline, imagery, CTA, form — is placed with conversion psychology in mind.",
    tagline: "One Page. One Goal. Maximum Conversions — Landing Pages That Actually Work",
    aboutUs: "Creators Touch Global has designed hundreds of landing pages for ad campaigns across healthcare, aesthetics, education, and retail. We know what works because we test everything — A/B tested headlines, optimised form fields, and CTA placement backed by real performance data.",
    benefits: [
      "Conversion-focused design with clear value proposition",
      "A/B tested headlines and CTA placements",
      "Mobile-optimised for ad traffic from all devices",
      "Lead capture forms with CRM integration",
      "Fast load times for better Quality Score on Google Ads",
      "Tracking setup with Google Analytics and Meta Pixel",
    ],
    keywords: ["landing page design", "lead generation page", "conversion landing page", "PPC landing page", "campaign page"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "prp-treatment"],
  },
  {
    slug: "best-responsive-web-design-in-vijayawada",
    title: "Responsive Web Design",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Websites that look and work perfectly on every screen — phone, tablet, and desktop.",
    longDesc: "Over 70% of your visitors are on mobile. We design websites that adapt fluidly to every screen size — from 4-inch phones to 32-inch monitors. No pinching, no scrolling sideways, no broken layouts. Just seamless experiences that convert regardless of device.",
    tagline: "Every Screen. Every Device. One Perfect Experience — Responsive Design Done Right",
    aboutUs: "Since 2008, Creators Touch Global has been building responsive websites long before it became a standard. Every site we deliver is tested across 20+ device configurations and optimised for Core Web Vitals. Our responsive designs don't just resize — they reorganise content for the best possible experience on each device.",
    benefits: [
      "Fluid layouts that adapt to any screen size",
      "Touch-friendly navigation and interactions for mobile",
      "Optimised images that load fast on slower connections",
      "Cross-browser testing on Chrome, Safari, Firefox, and Edge",
      "Core Web Vitals optimised for Google ranking signals",
      "Retina-ready graphics and crisp typography on all displays",
    ],
    keywords: ["responsive web design", "mobile-friendly website", "adaptive design", "mobile-first design", "responsive development"],
    relatedSlugs: ["threadlift", "rma", "meditron-cdc", "botox"],
  },
  {
    slug: "best-cms-website-design-in-vijayawada",
    title: "CMS Website Design",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Websites with easy-to-use content management — update anything yourself, anytime.",
    longDesc: "We build websites on WordPress, Strapi, and custom CMS platforms that let you update content, add pages, upload images, and manage your site without touching a line of code. Your team stays in control while we ensure the design stays beautiful.",
    tagline: "Update Your Website Yourself — No Developer Required, No Design Compromised",
    aboutUs: "Creators Touch Global has built hundreds of CMS-powered websites for businesses that need to update content regularly — hospitals with doctor listings, schools with event calendars, and retail brands with seasonal promotions. We train your team to manage the site confidently.",
    benefits: [
      "WordPress or custom CMS setup tailored to your needs",
      "Intuitive admin panel — no technical knowledge required",
      "Page builder for creating new pages without a developer",
      "Media library for easy image and document management",
      "Role-based access for team members and content editors",
      "Training session and documentation for your team",
    ],
    keywords: ["CMS website", "WordPress website", "content management system", "CMS development", "easy-to-manage website"],
    relatedSlugs: ["st-pauls-school", "meditron-cdc"],
  },
  {
    slug: "best-job-portal-website-in-vijayawada",
    title: "Job Portal Website",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Custom job portals that connect employers with the right candidates efficiently.",
    longDesc: "We design and develop job portal websites with advanced search, filtering, employer dashboards, candidate profiles, resume uploads, and application tracking. Whether you are building a niche job board or a regional recruitment platform, we deliver a scalable, user-friendly solution.",
    tagline: "Connect the Right People to the Right Jobs — Job Portals Built for Scale",
    aboutUs: "Creators Touch Global has built custom web applications and portals for businesses that need to manage complex workflows online. Our job portal solutions are designed for performance at scale — handling thousands of listings and applications without slowing down.",
    benefits: [
      "Employer and candidate registration with dashboards",
      "Advanced job search with filters for location, industry, and experience",
      "Resume upload and profile builder for candidates",
      "Application tracking system for employers",
      "Email notifications for new jobs and applications",
      "Admin panel for managing listings, users, and payments",
    ],
    keywords: ["job portal website", "recruitment website", "job board development", "employment portal", "career website"],
    relatedSlugs: ["meditron-cdc"],
  },
  {
    slug: "best-real-estate-website-portal-in-vijayawada",
    title: "Real Estate Website & Portal",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Property listing websites with search, maps, and lead capture built in.",
    longDesc: "We build real estate websites and portals with property listings, advanced search filters, map integration, virtual tours, and enquiry forms. Whether you are a developer, broker, or aggregator, we build platforms that help buyers find properties and help you capture leads.",
    tagline: "Every Property Deserves to Be Found — Real Estate Portals That Drive Enquiries",
    aboutUs: "Creators Touch Global has built property listing platforms and real estate websites for developers and brokers who need to showcase properties professionally online. Our solutions include map integration, search filters, and lead management tools that turn visitors into site visits.",
    benefits: [
      "Property listing pages with galleries, floor plans, and specifications",
      "Advanced search with filters for location, price, type, and size",
      "Google Maps integration with property location markers",
      "Lead capture forms with automated email notifications",
      "Agent/builder profile pages with contact details",
      "Admin panel for managing properties and enquiries",
    ],
    keywords: ["real estate website", "property portal", "real estate web development", "property listing website", "builder website"],
    relatedSlugs: ["meditron-cdc"],
  },
  {
    slug: "best-matrimony-website-in-vijayawada",
    title: "Matrimony Website",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Matrimony platforms with profile matching, search, and secure communication.",
    longDesc: "We build matrimony websites with user registration, profile creation, partner search with detailed filters, horoscope matching, secure messaging, and subscription plans. Whether community-specific or open, our matrimony platforms are built for trust and usability.",
    tagline: "Help People Find Their Perfect Match — Matrimony Platforms Built on Trust",
    aboutUs: "Creators Touch Global has developed web applications that handle complex user interactions, profile management, and secure communications. Our matrimony platform solutions are designed with privacy, security, and user experience at the core — because trust is everything in this space.",
    benefits: [
      "User registration with detailed profile creation",
      "Advanced partner search with community, education, and location filters",
      "Horoscope and compatibility matching features",
      "Secure in-platform messaging between verified profiles",
      "Subscription and payment plan management",
      "Admin dashboard for profile verification and moderation",
    ],
    keywords: ["matrimony website", "matchmaking website", "marriage portal", "matrimony web development", "wedding portal"],
    relatedSlugs: ["meditron-cdc"],
  },
  {
    slug: "best-redesigning-website-in-vijayawada",
    title: "Redesigning Website",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Give your outdated website a modern makeover — better design, faster performance, more leads.",
    longDesc: "If your website looks like it was built five years ago, it probably costs you customers every day. We redesign existing websites with modern layouts, faster performance, mobile responsiveness, and conversion-focused user flows — all while preserving your SEO equity and existing content.",
    tagline: "Your Website Is Costing You Customers — Let Us Fix That with a Modern Redesign",
    aboutUs: "Creators Touch Global has redesigned hundreds of websites for businesses that outgrew their original design. We audit your current site, identify what's working and what's not, and rebuild it with modern technology, better UX, and measurable performance improvements.",
    benefits: [
      "Full audit of your current website's design, speed, and SEO",
      "Modern, responsive redesign that reflects your current brand",
      "Content migration with SEO redirects to preserve rankings",
      "Speed optimisation for faster load times and better Core Web Vitals",
      "Conversion flow improvements based on user behaviour analysis",
      "Post-launch support and performance monitoring",
    ],
    keywords: ["website redesign", "website makeover", "website revamp", "modernise website", "website refresh"],
    relatedSlugs: ["st-pauls-school", "change-ngo"],
  },
  {
    slug: "best-website-maintenance-in-vijayawada",
    title: "Website Maintenance",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Keep your website secure, fast, and up-to-date with ongoing maintenance plans.",
    longDesc: "Websites need regular care — security updates, plugin patches, content updates, performance monitoring, and backup management. Our maintenance plans keep your website running smoothly so you can focus on your business, not your server.",
    tagline: "Your Website Runs 24/7 — Make Sure Someone Is Looking After It",
    aboutUs: "Creators Touch Global provides ongoing website maintenance for businesses across India, the UK, and UAE. We monitor uptime, apply security patches, update plugins, fix bugs, and handle content changes — so your website is always fast, secure, and current.",
    benefits: [
      "Regular security updates and vulnerability patches",
      "Daily backups with quick restore capability",
      "Uptime monitoring with instant downtime alerts",
      "Content updates — text, images, pages — as needed",
      "Performance monitoring and speed optimisation",
      "Monthly maintenance reports with actionable recommendations",
    ],
    keywords: ["website maintenance", "website support", "website management", "site maintenance plan", "website care"],
    relatedSlugs: ["meditron-cdc", "st-pauls-school"],
  },
  {
    slug: "best-wordpress-development-in-vijayawada",
    title: "WordPress Development",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Custom WordPress websites — no templates, no bloat, just clean, fast, manageable sites.",
    longDesc: "We build custom WordPress websites from scratch — no pre-made templates, no bloated page builders. Every theme is hand-coded for speed, security, and maintainability. You get a WordPress site that loads fast, ranks well, and lets you manage content effortlessly through the admin panel.",
    tagline: "WordPress Without the Bloat — Custom-Built, Fast, and Easy to Manage",
    aboutUs: "Creators Touch Global has been building WordPress websites since 2008. We have built everything from simple business sites to complex multi-language portals. Our approach: custom theme development, minimal plugins, clean code, and a CMS setup your team can actually use.",
    benefits: [
      "Custom WordPress theme development — no templates",
      "Clean, lightweight code for fast load times",
      "Advanced Custom Fields for flexible content management",
      "WooCommerce integration for e-commerce functionality",
      "Security hardening and performance optimisation",
      "SEO-ready with schema markup and clean URL structure",
    ],
    keywords: ["WordPress development", "custom WordPress", "WordPress website", "WordPress developer", "WordPress design"],
    relatedSlugs: ["st-pauls-school", "change-ngo", "meditron-cdc"],
  },
  {
    slug: "best-shopify-store-design-in-vijayawada",
    title: "Shopify Store Design",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Beautiful Shopify stores that turn browsers into buyers — setup to launch in weeks.",
    longDesc: "We design and set up Shopify stores that look premium, load fast, and convert visitors into customers. From theme customisation and product catalogue setup to payment gateway integration and shipping configuration — we handle everything so you can start selling.",
    tagline: "Launch Your Shopify Store — Designed to Sell, Built to Scale",
    aboutUs: "Creators Touch Global has set up Shopify stores for brands in India, the UK, and UAE. We know Shopify inside out — from Liquid theme development to app integrations, payment setups, and conversion optimisation. Our stores are designed to sell, not just display.",
    benefits: [
      "Custom Shopify theme design or premium theme customisation",
      "Product catalogue setup with variants, collections, and tags",
      "Payment gateway integration — Razorpay, Stripe, PayPal",
      "Shipping rate configuration and courier integration",
      "SEO setup with optimised titles, descriptions, and URLs",
      "Staff training on Shopify admin and order management",
    ],
    keywords: ["Shopify store design", "Shopify development", "Shopify setup", "Shopify expert", "Shopify store"],
    relatedSlugs: ["fillers-skin", "threadlift"],
  },
  {
    slug: "best-next-js-development-in-vijayawada",
    title: "Next.js Development",
    category: "Web Design & Development",
    color: "#FF3D8F",
    shortDesc: "Lightning-fast websites built with Next.js — the framework behind the fastest sites on the web.",
    longDesc: "We build high-performance websites and web applications with Next.js — React's production framework. Server-side rendering, static generation, API routes, and edge deployment — all resulting in websites that score 95+ on Lighthouse and rank higher on Google.",
    tagline: "The Fastest Websites on the Internet Are Built with Next.js — We Build Them for You",
    aboutUs: "Creators Touch Global uses Next.js for clients who demand the absolute best in performance, SEO, and scalability. This very website is built with Next.js. We combine React's component architecture with server-side rendering for websites that are blazing fast and developer-friendly.",
    benefits: [
      "Server-side rendering for instant page loads and better SEO",
      "Static site generation for pages that load in milliseconds",
      "React component architecture for maintainable, scalable code",
      "API routes for backend functionality without a separate server",
      "Image optimisation and lazy loading built in",
      "Edge deployment for global performance",
    ],
    keywords: ["Next.js development", "Next.js website", "React development", "server-side rendering", "JAMstack"],
    relatedSlugs: ["threadlift", "rma", "fillers-skin", "botox", "kensley-aesthetics"],
  },

  // ─── Design & Branding ────────────────────────────────────────────
  {
    slug: "best-brand-identity-in-vijayawada",
    title: "Brand Identity",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Complete brand identities that make your business instantly recognisable and memorable.",
    longDesc: "A logo is just a mark — a brand is the entire experience. We create complete brand identities including logo design, colour systems, typography, brand voice, and visual guidelines that make your business consistently recognisable across every touchpoint.",
    tagline: "A Logo Is a Mark. A Brand Is a Feeling. We Build Both — From the Ground Up",
    aboutUs: "Since 2008, Creators Touch Global has crafted brand identities for hospitals, jewellers, schools, NGOs, and aesthetics clinics across five countries. From Anjaneya Jewellery's heritage-inspired identity to the premium positioning of Fillers Skin — every brand we build is designed to be remembered.",
    benefits: [
      "Brand strategy and positioning workshops",
      "Logo design with multiple concept explorations",
      "Complete colour palette and typography system",
      "Brand voice and messaging guidelines",
      "Visual identity across digital and print touchpoints",
      "Brand guidelines document for consistent usage",
    ],
    keywords: ["brand identity", "branding", "brand design", "brand strategy", "visual identity"],
    relatedSlugs: ["fillers-skin", "change-ngo", "kensley-aesthetics"],
  },
  {
    slug: "best-logo-design-in-vijayawada",
    title: "Logo Design",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Iconic logos that hold their shape from a business card to a billboard.",
    longDesc: "Your logo is the face of your brand. We design logos that are simple, memorable, versatile, and timeless. Every logo goes through multiple rounds of exploration — from initial concepts to final refinement — ensuring you get a mark that represents your business perfectly.",
    tagline: "The Best Logos Are the Simplest — We Design Marks That Last Decades",
    aboutUs: "Creators Touch Global has designed logos for over 500 businesses since 2008 — from startups finding their identity to heritage brands modernising theirs. Our logos work at every scale: embroidered on uniforms, etched on jewellery, printed on billboards, and displayed on screens.",
    benefits: [
      "Multiple initial concept explorations",
      "Typography-led, icon-led, or combination marks",
      "Colour and monochrome versions",
      "Scalable vector files for print and digital use",
      "Brand mark variations for different contexts",
      "Final delivery in AI, EPS, SVG, PNG, and PDF formats",
    ],
    keywords: ["logo design", "custom logo", "brand logo", "logo designer", "professional logo"],
    relatedSlugs: ["fillers-skin", "change-ngo", "threadlift"],
  },
  {
    slug: "best-package-design-in-vijayawada",
    title: "Package Design",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Packaging that stands out on shelves and creates an unboxing experience worth sharing.",
    longDesc: "Great packaging sells before the product does. We design product packaging that catches the eye on the shelf, communicates value at a glance, and creates an unboxing experience customers want to share. From concept to print-ready artwork, we handle every detail.",
    tagline: "The Package Is the First Product Your Customer Holds — Make It Unforgettable",
    aboutUs: "Creators Touch Global designs packaging for food brands, cosmetics, jewellery, and consumer products. We understand the science behind shelf impact — colour psychology, typography hierarchy, and material choices that make your product the one customers reach for.",
    benefits: [
      "Packaging concept development and ideation",
      "Structural design for boxes, pouches, bottles, and labels",
      "Print-ready artwork with die-cut templates",
      "Material and finish recommendations",
      "Mockups for presentation and approval",
      "Coordination with printers for production quality",
    ],
    keywords: ["package design", "packaging design", "product packaging", "box design", "label design"],
    relatedSlugs: ["fillers-skin"],
  },
  {
    slug: "best-graphic-design-in-vijayawada",
    title: "Graphic Design",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Professional graphic design for every business need — digital, print, and beyond.",
    longDesc: "From social media graphics and ad creatives to print collateral and presentation decks — we handle all your visual design needs. Our in-house design team delivers consistent, on-brand graphics that communicate your message clearly and professionally.",
    tagline: "Design That Communicates, Not Just Decorates — Graphics That Get Results",
    aboutUs: "Creators Touch Global's in-house design team has produced thousands of graphics for businesses across healthcare, retail, education, and aesthetics. We work fast, maintain brand consistency, and deliver files in every format you need.",
    benefits: [
      "Social media graphics and post designs",
      "Ad creatives for Google Display and Meta",
      "Print collateral — flyers, posters, banners",
      "Presentation and pitch deck design",
      "Event and exhibition graphics",
      "Consistent brand application across all materials",
    ],
    keywords: ["graphic design", "graphic designer", "visual design", "design agency", "print design"],
    relatedSlugs: ["kensley-aesthetics", "change-ngo"],
  },
  {
    slug: "best-infographics-in-vijayawada",
    title: "Infographics",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Data-driven infographics that make complex information simple and shareable.",
    longDesc: "We design infographics that turn dense data, complex processes, and detailed information into clear, visually engaging graphics that people actually want to read and share. Perfect for reports, presentations, social media, and content marketing.",
    tagline: "Turn Data Into Stories People Actually Want to Read — Infographics That Inform and Inspire",
    aboutUs: "Creators Touch Global creates infographics for healthcare organisations, educational institutions, and businesses that need to communicate complex information simply. Our infographics are designed for clarity first, beauty second — because an infographic that looks great but confuses the reader has failed.",
    benefits: [
      "Data visualisation with clear, accurate charts and graphs",
      "Process and workflow infographics",
      "Comparison and timeline infographics",
      "Statistical infographics for reports and presentations",
      "Social media-optimised formats for sharing",
      "Print-ready versions for presentations and publications",
    ],
    keywords: ["infographic design", "data visualisation", "infographics", "visual data", "information design"],
    relatedSlugs: ["meditron-cdc", "change-ngo"],
  },
  {
    slug: "best-brochure-design-in-vijayawada",
    title: "Brochure Design",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Professional brochures that tell your story and leave a lasting impression.",
    longDesc: "We design brochures that work as powerful sales tools — bi-fold, tri-fold, multi-page, and digital formats. Every brochure is crafted with compelling copy, professional imagery, and clean layouts that guide the reader from interest to action.",
    tagline: "A Brochure Is a Salesperson That Never Takes a Day Off — We Design the Best Ones",
    aboutUs: "Creators Touch Global has designed brochures for hospitals, schools, real estate developers, and retail brands. We handle everything from copywriting and photography direction to layout design and print coordination — delivering brochures that your sales team actually wants to hand out.",
    benefits: [
      "Bi-fold, tri-fold, and multi-page brochure design",
      "Compelling copy and content structure",
      "Professional photography direction and image sourcing",
      "Print-ready files with bleed and crop marks",
      "Digital PDF versions for email and web sharing",
      "Coordination with printers for quality output",
    ],
    keywords: ["brochure design", "company brochure", "product brochure", "tri-fold brochure", "brochure printing"],
    relatedSlugs: ["st-pauls-school"],
  },
  {
    slug: "best-social-media-pack-in-vijayawada",
    title: "Social Media Pack",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Ready-to-use social media templates that keep your brand consistent across every platform.",
    longDesc: "We create comprehensive social media design packs — branded templates for posts, stories, carousels, covers, and highlights. Your team gets a library of on-brand templates they can customise and post, ensuring your social media always looks professional and consistent.",
    tagline: "Look Professional on Every Platform — Social Media Packs That Keep Your Brand Consistent",
    aboutUs: "Creators Touch Global creates social media design systems for brands that post regularly and need to maintain visual consistency. Our packs include templates for every format — Instagram posts, stories, LinkedIn banners, Facebook covers — all designed in your brand's visual language.",
    benefits: [
      "Branded templates for posts, stories, and carousels",
      "Platform-specific sizes for Instagram, Facebook, LinkedIn",
      "Cover image designs for all social media profiles",
      "Highlight cover icons for Instagram",
      "Editable Canva or Figma templates for your team",
      "Brand consistency guidelines for social media",
    ],
    keywords: ["social media pack", "social media templates", "social media design", "Instagram templates", "brand social media kit"],
    relatedSlugs: ["kensley-aesthetics", "change-ngo"],
  },
  {
    slug: "best-newsletter-design-in-vijayawada",
    title: "Newsletter Design",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Email newsletter designs that get opened, read, and clicked — every time.",
    longDesc: "We design email newsletters that look professional across every email client — Gmail, Outlook, Apple Mail, and mobile. From layout and imagery to subject line strategy and CTA placement, we create newsletters that your subscribers actually want to open.",
    tagline: "Emails That Get Opened, Read, and Clicked — Newsletter Design That Performs",
    aboutUs: "Creators Touch Global designs email newsletters for businesses that use email as a core communication and marketing channel. We understand the technical constraints of email rendering and design within those limits to create newsletters that look great everywhere.",
    benefits: [
      "Custom newsletter template design",
      "Responsive layouts for desktop and mobile email clients",
      "Cross-client compatibility testing",
      "CTA placement optimised for click-through",
      "HTML email coding for Mailchimp, SendGrid, or custom platforms",
      "Template library for recurring newsletter editions",
    ],
    keywords: ["newsletter design", "email newsletter", "email template design", "newsletter template", "email marketing design"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-web-banners-in-vijayawada",
    title: "Web Banners",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Eye-catching web banners and display ads that drive clicks and conversions.",
    longDesc: "We design web banners for Google Display Network, social media ads, website headers, and promotional campaigns. Every banner is designed for maximum visual impact within the constraints of the format — clear messaging, compelling imagery, and strong CTAs.",
    tagline: "Banners That Stop the Scroll and Start the Click — Display Ads That Convert",
    aboutUs: "Creators Touch Global designs web banners and display ad creatives for businesses running Google Display, Facebook, and Instagram ad campaigns. We create banner sets in all standard IAB sizes, optimised for file size and visual impact.",
    benefits: [
      "Google Display Network banner sets in all IAB sizes",
      "Social media ad creatives for Meta and LinkedIn",
      "Animated and static banner options",
      "A/B test variations for performance optimisation",
      "Website hero banners and promotional headers",
      "Retina-ready exports for high-density displays",
    ],
    keywords: ["web banner design", "display ad design", "banner ads", "Google Display ads", "digital banners"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "fillers-skin"],
  },
  {
    slug: "best-powerpoint-presentation-in-vijayawada",
    title: "Powerpoint Presentation",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Presentation decks that win pitches, impress investors, and close deals.",
    longDesc: "We design professional PowerPoint and Google Slides presentations that make your content shine. From investor pitch decks and sales presentations to conference talks and internal reports — we create decks that communicate with clarity and visual authority.",
    tagline: "Your Ideas Deserve a Better Slide — Presentations That Win Rooms",
    aboutUs: "Creators Touch Global has designed presentations for startups pitching investors, hospitals presenting to boards, and sales teams closing enterprise deals. We turn complex information into clear, compelling visual narratives that keep audiences engaged.",
    benefits: [
      "Custom slide design matching your brand identity",
      "Data visualisation with clear charts and diagrams",
      "Investor pitch deck structure and storytelling",
      "Master template with reusable slide layouts",
      "Speaker notes and presentation flow guidance",
      "Delivery in PowerPoint, Google Slides, and PDF formats",
    ],
    keywords: ["presentation design", "PowerPoint design", "pitch deck", "slide design", "Google Slides"],
    relatedSlugs: ["meditron-cdc", "change-ngo"],
  },
  {
    slug: "best-e-mail-template-in-vijayawada",
    title: "E-Mail Template",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Professional email templates that render perfectly across every email client.",
    longDesc: "We design and code custom email templates that work flawlessly across Gmail, Outlook, Apple Mail, Yahoo, and mobile clients. From transactional emails to promotional campaigns, every template is built with clean HTML tables, inline CSS, and thorough cross-client testing.",
    tagline: "Emails That Look Perfect Everywhere — Templates Built for Every Inbox",
    aboutUs: "Creators Touch Global builds email templates for e-commerce order confirmations, appointment reminders, promotional campaigns, and newsletters. We know the quirks of every email client and code around them — so your emails always render as designed.",
    benefits: [
      "Custom HTML email template design and coding",
      "Responsive design for desktop and mobile rendering",
      "Cross-client testing across 20+ email platforms",
      "Integration with Mailchimp, SendGrid, or your ESP",
      "Transactional email templates (confirmations, receipts, reminders)",
      "Promotional campaign templates with editable sections",
    ],
    keywords: ["email template", "HTML email", "email design", "email template design", "responsive email"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-brand-guidelines-in-vijayawada",
    title: "Brand Guidelines",
    category: "Design & Branding",
    color: "#29A8DC",
    shortDesc: "Comprehensive brand guidelines that ensure consistency across every touchpoint.",
    longDesc: "We create detailed brand guideline documents that define how your brand looks, sounds, and feels across every medium. Logo usage rules, colour specifications, typography scales, image style, tone of voice — everything your team and partners need to represent your brand correctly.",
    tagline: "Consistency Builds Trust — Brand Guidelines That Keep Your Identity Intact",
    aboutUs: "Creators Touch Global creates brand guideline documents for businesses that need their brand applied consistently across teams, agencies, and markets. Our guidelines are practical and actionable — not just beautiful PDFs that nobody reads.",
    benefits: [
      "Logo usage rules with clear dos and don'ts",
      "Colour palette with HEX, RGB, CMYK, and Pantone values",
      "Typography system with font hierarchy and sizing",
      "Image and photography style guidelines",
      "Tone of voice and messaging framework",
      "Application examples for digital and print",
    ],
    keywords: ["brand guidelines", "brand book", "style guide", "brand standards", "brand manual"],
    relatedSlugs: ["fillers-skin", "kensley-aesthetics"],
  },

  // ─── Digital Marketing ────────────────────────────────────────────
  {
    slug: "best-local-search-seo-in-vijayawada",
    title: "Local Search SEO",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Dominate local search results — be the first business your neighbours find online.",
    longDesc: "We optimise your business for local search so you appear in Google Maps, local pack results, and 'near me' searches. From Google Business Profile optimisation to local citations and reviews management, we make sure your business is the first one people find in your area.",
    tagline: "When Your Neighbours Search, You Should Be First — Local SEO That Delivers",
    aboutUs: "Creators Touch Global has helped 2000+ businesses rank in local search results across India, the UK, and UAE. We built Meditron CDC's local SEO to rank for 40+ keywords across 7 cities. We know local SEO because we have done it at scale.",
    benefits: [
      "Google Business Profile setup and optimisation",
      "Local citation building across directories and platforms",
      "Review generation and reputation management strategy",
      "Local keyword research and on-page optimisation",
      "NAP consistency audit across all online listings",
      "Monthly local ranking reports with competitor tracking",
    ],
    keywords: ["local SEO", "local search optimisation", "Google Business Profile", "near me SEO", "local search marketing"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-search-engine-marketing-in-vijayawada",
    title: "Search Engine Marketing",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Paid search campaigns that put your business at the top of Google — instantly.",
    longDesc: "We run search engine marketing campaigns on Google that target high-intent keywords your customers are actively searching. From campaign setup and keyword bidding to ad copy testing and conversion tracking, we manage every aspect of your paid search to maximise ROI.",
    tagline: "Skip the Queue — Get to the Top of Google Today with Paid Search",
    aboutUs: "Creators Touch Global is a Google Certified Partner managing paid search campaigns for clinics, e-commerce brands, and service businesses. We don't just set up ads — we continuously optimise bids, test ad copies, and refine targeting to squeeze maximum value from every rupee.",
    benefits: [
      "Google Search Ads targeting high-intent buyer keywords",
      "Keyword research and competitive analysis",
      "Ad copy writing with A/B testing",
      "Bid management and budget optimisation",
      "Conversion tracking with Google Analytics setup",
      "Monthly performance reports with ROI analysis",
    ],
    keywords: ["search engine marketing", "SEM", "Google Ads", "paid search", "PPC advertising"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "prp-treatment"],
  },
  {
    slug: "best-google-adwords-in-vijayawada",
    title: "Google Adwords",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Expert Google Ads management that turns your ad spend into measurable revenue.",
    longDesc: "We set up, manage, and optimise Google Ads campaigns across Search, Display, Shopping, and YouTube. Every campaign is built around your business goals — whether that's leads, sales, calls, or foot traffic. We track every conversion so you know exactly what your ads deliver.",
    tagline: "Every Click Tracked, Every Rupee Accounted For — Google Ads That Pay for Themselves",
    aboutUs: "As a Google Certified Partner, Creators Touch Global manages Google Ads campaigns for businesses spending from Rs 10,000 to Rs 10,00,000 per month. We have managed campaigns for aesthetics clinics, hospitals, jewellers, schools, and e-commerce brands — always with transparent reporting and measurable ROI.",
    benefits: [
      "Google Search, Display, and Shopping campaign setup",
      "Keyword strategy with negative keyword management",
      "Ad copywriting with extensions and sitelinks",
      "Landing page recommendations for better Quality Score",
      "Remarketing campaigns for warm audience re-engagement",
      "Transparent monthly reports with spend and conversion data",
    ],
    keywords: ["Google Adwords", "Google Ads management", "PPC management", "Google advertising", "AdWords agency"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "fillers-skin", "prp-treatment"],
  },
  {
    slug: "best-social-media-optimization-in-vijayawada",
    title: "Social Media Optimization",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Optimise your social media profiles and content for maximum visibility and engagement.",
    longDesc: "We optimise your social media presence across Instagram, Facebook, LinkedIn, and YouTube — from profile setup and bio optimisation to hashtag strategy and content scheduling. The goal: more visibility, more followers, and more engagement from the right audience.",
    tagline: "Your Social Media Should Work as Hard as You Do — We Make Sure It Does",
    aboutUs: "Creators Touch Global manages social media optimisation for brands across healthcare, aesthetics, education, and retail. We go beyond posting — we optimise every element of your social presence for discoverability, engagement, and conversion.",
    benefits: [
      "Profile optimisation across all social platforms",
      "Bio and description writing with keyword integration",
      "Hashtag research and strategy for discoverability",
      "Content calendar planning and scheduling",
      "Engagement tactics to grow followers organically",
      "Analytics setup and monthly performance tracking",
    ],
    keywords: ["social media optimization", "SMO", "social media strategy", "Instagram optimization", "social media growth"],
    relatedSlugs: ["kensley-aesthetics", "change-ngo"],
  },
  {
    slug: "best-search-engine-optimization-in-vijayawada",
    title: "Search Engine Optimization",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Rank higher on Google — organic traffic that compounds month after month.",
    longDesc: "We optimise your website to appear at the top of Google search results for the keywords your customers are actually searching. From technical SEO and on-page optimisation to content strategy and link building, we build a system that delivers compounding organic traffic.",
    tagline: "Dominate Google Search Results — We Make Sure Your Customers Find You First",
    aboutUs: "With 17+ years of experience, Creators Touch Global has helped over 2000 businesses rank on the first page of Google. We built Meditron CDC's website to rank for 40+ keywords on Google's first page. We know what works — because we have done it hundreds of times.",
    benefits: [
      "Comprehensive keyword research for your industry",
      "On-page SEO with optimised titles, meta tags, and headers",
      "Technical SEO audit — site speed, crawlability, indexing",
      "Content strategy aligned with search intent",
      "Quality backlink building and outreach",
      "Monthly ranking reports with competitor analysis",
    ],
    keywords: ["SEO services", "search engine optimization", "Google ranking", "organic SEO", "SEO agency"],
    relatedSlugs: ["meditron-cdc", "threadlift", "kensley-aesthetics"],
  },
  {
    slug: "best-social-media-marketing-in-vijayawada",
    title: "Social Media Marketing",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Strategic social media marketing that builds your brand and drives measurable results.",
    longDesc: "We create and execute social media marketing strategies that build brand awareness, drive engagement, and generate leads. From content creation and community management to paid social campaigns and influencer partnerships — we handle everything.",
    tagline: "Build a Brand People Follow, Trust, and Buy From — Social Media Done Right",
    aboutUs: "Creators Touch Global manages social media marketing for brands across India, the UK, and UAE. We have grown clinic Instagram accounts from zero to thousands of engaged followers, and generated measurable leads through strategic social media campaigns.",
    benefits: [
      "Custom social media strategy aligned with business goals",
      "Content creation — posts, stories, Reels, and carousels",
      "Community management and audience engagement",
      "Paid social campaigns on Facebook and Instagram",
      "Influencer identification and partnership management",
      "Monthly analytics and performance reports",
    ],
    keywords: ["social media marketing", "SMM", "social media agency", "Instagram marketing", "Facebook marketing"],
    relatedSlugs: ["kensley-aesthetics", "change-ngo", "dr-matla"],
  },
  {
    slug: "best-pay-per-click-management-in-vijayawada",
    title: "Pay Per Click Management",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "PPC campaigns that deliver clicks that convert — not just impressions that cost.",
    longDesc: "We manage pay-per-click campaigns across Google, Facebook, and Instagram with a laser focus on ROI. Every click is tracked, every keyword is monitored, and every ad is optimised to deliver the highest possible return on your advertising spend.",
    tagline: "Stop Wasting Ad Spend — PPC Management That Delivers Real Returns",
    aboutUs: "Creators Touch Global manages PPC campaigns for businesses that need measurable results from their advertising. As a Google Certified Partner, we bring platform expertise, data-driven optimisation, and transparent reporting to every campaign we manage.",
    benefits: [
      "Campaign setup across Google Ads and Meta Ads",
      "Keyword and audience targeting strategy",
      "Ad creative development and A/B testing",
      "Bid management and budget allocation",
      "Conversion tracking and attribution setup",
      "Weekly optimisation and monthly ROI reports",
    ],
    keywords: ["PPC management", "pay per click", "PPC agency", "Google Ads management", "paid advertising"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "prp-treatment", "fillers-skin"],
  },
  {
    slug: "best-online-reputation-management-in-vijayawada",
    title: "Online Reputation Management",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Protect and build your brand's reputation across Google, social media, and review platforms.",
    longDesc: "We monitor, manage, and improve your online reputation across Google Reviews, social media, and industry directories. From review generation and response management to crisis communication and brand monitoring — we ensure your online presence reflects the quality of your business.",
    tagline: "Your Reputation Arrives Before You Do — Make Sure It Says the Right Things",
    aboutUs: "Creators Touch Global helps businesses manage their online reputation proactively. We have helped hospitals respond to patient reviews professionally, helped clinics generate positive Google reviews systematically, and helped brands monitor mentions across the web.",
    benefits: [
      "Google Reviews monitoring and response management",
      "Review generation strategy to increase positive reviews",
      "Brand mention monitoring across social and web",
      "Crisis communication planning and response",
      "Directory listing management and cleanup",
      "Monthly reputation scorecard and trend analysis",
    ],
    keywords: ["online reputation management", "ORM", "reputation management", "review management", "brand reputation"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-conversion-rate-optimization-in-vijayawada",
    title: "Conversion Rate Optimization",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Get more leads from the same traffic — optimise every page for conversions.",
    longDesc: "We analyse your website's user behaviour, identify conversion bottlenecks, and implement data-driven improvements that increase the percentage of visitors who take action. More leads, more sales, more bookings — from the traffic you are already getting.",
    tagline: "Your Traffic Is Fine — Your Conversion Rate Isn't. Let Us Fix That",
    aboutUs: "Creators Touch Global applies conversion rate optimisation to every website we build and manage. We use heatmaps, session recordings, A/B testing, and funnel analysis to identify exactly where visitors drop off — and fix it systematically.",
    benefits: [
      "Conversion audit with heatmap and session recording analysis",
      "Funnel analysis to identify drop-off points",
      "A/B testing of headlines, CTAs, forms, and layouts",
      "Form optimisation to reduce abandonment",
      "Page speed improvements for better engagement",
      "Monthly conversion reports with actionable recommendations",
    ],
    keywords: ["conversion rate optimization", "CRO", "website optimization", "A/B testing", "conversion optimization"],
    relatedSlugs: ["threadlift", "kensley-aesthetics", "fillers-skin"],
  },
  {
    slug: "best-marketing-automation-in-vijayawada",
    title: "Marketing Automation",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Automated marketing workflows that nurture leads and close sales — without manual effort.",
    longDesc: "We set up marketing automation workflows that send the right message to the right person at the right time — automatically. From email drip campaigns and lead scoring to abandoned cart recovery and re-engagement sequences, we build systems that work while you sleep.",
    tagline: "Set It Up Once, Sell Forever — Marketing Automation That Never Takes a Day Off",
    aboutUs: "Creators Touch Global builds marketing automation systems for businesses that want to scale their lead nurturing without scaling their team. We have set up automation for clinics, e-commerce brands, and service businesses — saving hours of manual follow-up every day.",
    benefits: [
      "Email drip campaigns for lead nurturing",
      "Lead scoring and segmentation setup",
      "Abandoned cart recovery sequences for e-commerce",
      "Re-engagement campaigns for inactive subscribers",
      "CRM integration for unified customer data",
      "Workflow mapping and automation platform setup",
    ],
    keywords: ["marketing automation", "email automation", "lead nurturing", "drip campaigns", "automated marketing"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-display-advertising-in-vijayawada",
    title: "Display Advertising",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Display ads that build brand awareness and keep your business top of mind.",
    longDesc: "We create and manage display advertising campaigns on Google Display Network that reach your target audience across millions of websites. From banner design and audience targeting to retargeting and performance optimisation — we make display ads work for your business.",
    tagline: "Be Everywhere Your Customers Are — Display Advertising That Builds and Converts",
    aboutUs: "Creators Touch Global runs display advertising campaigns for brands that need visibility beyond search. We design compelling banner creatives, set up precise audience targeting, and optimise campaigns for the metrics that matter — impressions for awareness, clicks for consideration, conversions for revenue.",
    benefits: [
      "Google Display Network campaign setup and management",
      "Banner design in all standard IAB sizes",
      "Audience targeting by demographics, interests, and behaviour",
      "Retargeting campaigns for website visitors",
      "Placement optimisation and brand safety controls",
      "Performance tracking with viewability and conversion metrics",
    ],
    keywords: ["display advertising", "banner advertising", "Google Display Network", "display ads", "programmatic advertising"],
    relatedSlugs: ["kensley-aesthetics", "threadlift", "fillers-skin"],
  },
  {
    slug: "best-whatsapp-automation-in-vijayawada",
    title: "WhatsApp Automation",
    category: "Digital Marketing",
    color: "#cc0066",
    shortDesc: "Automated WhatsApp messaging that responds, follows up, and converts — 24/7.",
    longDesc: "We set up WhatsApp Business API automation for your business — automated responses, appointment reminders, order confirmations, lead follow-ups, and broadcast messages. Every message is timed, personalised, and designed to move your customer closer to a purchase.",
    tagline: "Never Miss a Message, Never Lose a Lead — WhatsApp Automation That Works Round the Clock",
    aboutUs: "Creators Touch Global has set up WhatsApp automation for clinics, hospitals, and service businesses that handle hundreds of enquiries daily. Our automated systems respond instantly, send appointment reminders, and follow up on leads — saving hours of manual work every day.",
    benefits: [
      "WhatsApp Business API setup and verification",
      "Automated welcome messages and quick replies",
      "Appointment reminder and confirmation flows",
      "Order confirmation and delivery update messages",
      "Lead follow-up sequences with personalised messaging",
      "Broadcast messaging for promotions and announcements",
    ],
    keywords: ["WhatsApp automation", "WhatsApp Business API", "WhatsApp marketing", "automated messaging", "WhatsApp chatbot"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },

  // ─── Mobile Applications ──────────────────────────────────────────
  {
    slug: "best-android-app-development-in-vijayawada",
    title: "Android App Development",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "Native Android apps that are fast, reliable, and built for the Google Play Store.",
    longDesc: "We develop native Android applications using Kotlin and Java that deliver smooth performance, intuitive navigation, and seamless integration with device features. From concept and design to development, testing, and Play Store launch — we handle the entire process.",
    tagline: "80% of India Uses Android — Make Sure Your App Is There",
    aboutUs: "Creators Touch Global has built Android applications for healthcare providers, service businesses, and consumer brands. Our apps are built for performance, security, and scalability — tested across multiple Android versions and device configurations before launch.",
    benefits: [
      "Native Android development with Kotlin/Java",
      "Material Design UI for consistent Android experience",
      "Integration with device features — camera, GPS, notifications",
      "API integration with your existing backend systems",
      "Google Play Store submission and optimisation",
      "Post-launch support and version updates",
    ],
    keywords: ["Android app development", "Android developer", "Android application", "Play Store app", "mobile app development"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-ios-app-development-in-vijayawada",
    title: "iOS App Development",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "Polished iOS apps built with Swift for the Apple App Store.",
    longDesc: "We build native iOS applications using Swift that feel at home on iPhone and iPad. From user interface design following Apple's Human Interface Guidelines to Core Data, Push Notifications, and App Store submission — we deliver iOS apps that Apple approves and users love.",
    tagline: "iPhone Users Expect Premium — We Build iOS Apps That Deliver",
    aboutUs: "Creators Touch Global develops iOS applications for businesses that need a premium mobile presence on Apple devices. Our iOS apps follow Apple's design guidelines, pass App Store review requirements, and deliver the smooth, responsive experience iPhone users expect.",
    benefits: [
      "Native iOS development with Swift",
      "UI design following Apple Human Interface Guidelines",
      "Push notifications and background processing",
      "Integration with Apple Pay, HealthKit, and other frameworks",
      "App Store submission and approval support",
      "Ongoing maintenance and iOS version compatibility updates",
    ],
    keywords: ["iOS app development", "iPhone app", "iPad app", "Swift development", "App Store app"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-flutter-app-development-in-vijayawada",
    title: "Flutter App Development",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "Cross-platform apps with Flutter — one codebase, native performance on both iOS and Android.",
    longDesc: "We build cross-platform mobile apps with Flutter — Google's UI toolkit that lets us deliver native-quality apps for both iOS and Android from a single codebase. Faster development, lower cost, and consistent experience across platforms.",
    tagline: "One Codebase. Two Platforms. Native Performance — Flutter Apps That Do It All",
    aboutUs: "Creators Touch Global uses Flutter for clients who need apps on both iOS and Android without doubling their development budget. Flutter's hot reload and widget system let us iterate quickly and deliver polished apps in less time than traditional native development.",
    benefits: [
      "Single codebase for iOS and Android",
      "Native-like performance with Flutter's rendering engine",
      "Custom UI widgets for a unique, branded experience",
      "Hot reload for rapid development and iteration",
      "Firebase integration for authentication, database, and analytics",
      "Play Store and App Store submission from the same project",
    ],
    keywords: ["Flutter app development", "Flutter developer", "cross-platform app", "Flutter mobile app", "Dart development"],
    relatedSlugs: ["meditron-cdc"],
  },
  {
    slug: "best-react-native-app-development-in-vijayawada",
    title: "React Native App Development",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "React Native apps that feel native — one team, two platforms, faster delivery.",
    longDesc: "We develop mobile apps with React Native that share code between iOS and Android while delivering native performance. Our React Native apps use platform-specific components where it matters, ensuring your app feels right at home on both operating systems.",
    tagline: "The React You Know, Now on Mobile — Apps That Feel Native Because They Are",
    aboutUs: "Creators Touch Global uses React Native for clients who already have React-based web applications and want to extend their platform to mobile. Code sharing between web and mobile means faster development, easier maintenance, and a unified technology stack.",
    benefits: [
      "Shared codebase for iOS and Android development",
      "Native components for platform-specific feel",
      "Code sharing with React web applications",
      "Over-the-air updates without App Store resubmission",
      "Third-party library ecosystem for rapid feature development",
      "Testing and deployment pipeline setup",
    ],
    keywords: ["React Native app", "React Native development", "cross-platform mobile", "React Native developer", "mobile app React"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-hybrid-app-development-in-vijayawada",
    title: "Hybrid App Development",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "Hybrid apps that work everywhere — mobile, tablet, and desktop from one build.",
    longDesc: "We build hybrid applications using Ionic and Capacitor that run on iOS, Android, and the web from a single codebase. Ideal for businesses that need cross-platform presence quickly and cost-effectively without sacrificing functionality.",
    tagline: "One App, Every Platform — Hybrid Development for Maximum Reach at Minimum Cost",
    aboutUs: "Creators Touch Global builds hybrid apps for businesses that need to reach users across multiple platforms without maintaining separate codebases. Our hybrid apps use web technologies wrapped in native containers — delivering app store presence and native features at a fraction of native development cost.",
    benefits: [
      "Single codebase for iOS, Android, and web",
      "Access to native device features via plugins",
      "Faster development timeline than native apps",
      "Lower development and maintenance costs",
      "App Store and Play Store distribution",
      "Progressive enhancement for web deployment",
    ],
    keywords: ["hybrid app development", "Ionic app", "Capacitor app", "cross-platform development", "hybrid mobile app"],
    relatedSlugs: ["meditron-cdc"],
  },
  {
    slug: "best-progressive-web-apps-in-vijayawada",
    title: "Progressive Web Apps",
    category: "Mobile Applications",
    color: "#96BF48",
    shortDesc: "Web apps that work like native apps — installable, offline-capable, and lightning fast.",
    longDesc: "We build Progressive Web Apps (PWAs) that combine the best of websites and native apps. Installable on the home screen, working offline, sending push notifications, and loading instantly — all without requiring an app store download.",
    tagline: "The Future of Apps Is Already Here — PWAs That Load Instantly and Work Everywhere",
    aboutUs: "Creators Touch Global builds PWAs for businesses that want app-like experiences without the friction of app store downloads. Our PWAs are built with service workers, web app manifests, and modern JavaScript — delivering native-like performance from the browser.",
    benefits: [
      "Installable on home screen without app store",
      "Offline functionality with service worker caching",
      "Push notifications for re-engagement",
      "Instant loading with app shell architecture",
      "Automatic updates without user intervention",
      "Works across all modern browsers and devices",
    ],
    keywords: ["progressive web app", "PWA development", "web app", "installable web app", "offline web app"],
    relatedSlugs: ["meditron-cdc", "threadlift", "kensley-aesthetics"],
  },

  // ─── Content Writing Services ─────────────────────────────────────
  {
    slug: "best-article-writing-in-vijayawada",
    title: "Article Writing",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Well-researched articles that establish authority and drive organic search traffic.",
    longDesc: "We write in-depth, SEO-optimised articles that position your brand as an authority in your industry. Every article is researched, structured for readability, and optimised for the keywords your audience is searching — driving organic traffic that compounds over time.",
    tagline: "Content That Ranks, Reads, and Converts — Articles Written by People Who Know Your Industry",
    aboutUs: "Creators Touch Global's content team writes articles for healthcare, aesthetics, education, and technology brands. We don't just write — we research your industry, understand your audience, and create content that answers the questions your customers are actually asking.",
    benefits: [
      "In-depth research on your industry and topic",
      "SEO-optimised structure with targeted keywords",
      "Clear, engaging writing in your brand's voice",
      "Internal linking strategy for site architecture",
      "Meta titles and descriptions for each article",
      "Regular content calendar for consistent publishing",
    ],
    keywords: ["article writing", "blog articles", "SEO articles", "content writing", "article writing service"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-content-writing-in-vijayawada",
    title: "Content Writing",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Professional content writing that communicates your brand's value with clarity and purpose.",
    longDesc: "We write website content, service pages, about us pages, and landing page copy that communicates your brand's value clearly and persuasively. Every word is chosen to inform, engage, and convert — no filler, no jargon, just content that works.",
    tagline: "Words That Work — Content Writing That Informs, Engages, and Converts",
    aboutUs: "Creators Touch Global writes content for websites, service pages, and marketing materials across healthcare, aesthetics, education, and retail. Our writers understand SEO, conversion psychology, and brand voice — delivering content that serves both search engines and human readers.",
    benefits: [
      "Website content — homepage, about, services, and more",
      "Service page content with clear value propositions",
      "Landing page copy optimised for conversions",
      "Brand voice development and tone consistency",
      "SEO integration with natural keyword placement",
      "Content editing and proofreading",
    ],
    keywords: ["content writing", "website content", "copywriting services", "professional writing", "web content"],
    relatedSlugs: ["threadlift", "rma", "meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-email-marketing-services-in-vijayawada",
    title: "Email Marketing Services",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Email campaigns that land in inboxes, get opened, and drive real revenue.",
    longDesc: "We plan, write, design, and send email marketing campaigns that generate measurable results. From welcome sequences and promotional campaigns to newsletters and abandoned cart recovery — we build email programs that keep your audience engaged and buying.",
    tagline: "The Highest ROI Channel in Marketing — Email Done Right",
    aboutUs: "Creators Touch Global manages email marketing for e-commerce brands, clinics, and service businesses. We know what makes people open, click, and buy from emails — and we apply that knowledge to every campaign we send.",
    benefits: [
      "Email strategy and campaign planning",
      "Copywriting for campaigns, sequences, and newsletters",
      "Email template design and HTML coding",
      "List segmentation and personalisation",
      "A/B testing of subject lines, content, and send times",
      "Performance analytics with open rate and conversion tracking",
    ],
    keywords: ["email marketing", "email campaigns", "email marketing services", "newsletter marketing", "email automation"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-content-marketing-services-in-vijayawada",
    title: "Content Marketing Services",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Strategic content that builds trust, drives traffic, and generates leads over time.",
    longDesc: "We create and distribute valuable, relevant content that attracts your target audience, builds authority, and drives profitable customer action. From blog strategy and SEO content to video scripts and lead magnets — we build content systems that compound.",
    tagline: "Content That Builds Trust Before the Sales Call — Marketing That Earns Attention",
    aboutUs: "Creators Touch Global builds content marketing strategies for businesses that understand the value of long-term brand building. We have built content systems for healthcare brands, aesthetics clinics, and e-commerce businesses that generate organic traffic and leads month after month.",
    benefits: [
      "Content strategy aligned with business goals and audience needs",
      "Blog content calendar with SEO-targeted topics",
      "Lead magnet creation — guides, checklists, ebooks",
      "Content distribution across owned and earned channels",
      "Performance tracking with traffic and lead attribution",
      "Quarterly content audits and strategy refinement",
    ],
    keywords: ["content marketing", "content strategy", "content marketing agency", "blog marketing", "inbound marketing"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-product-descriptions-in-vijayawada",
    title: "Product Descriptions",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Product descriptions that sell — clear, persuasive, and SEO-optimised.",
    longDesc: "We write product descriptions that do more than list features — they communicate value, create desire, and drive purchases. Every description is written with your target customer in mind, optimised for search, and structured for scannability.",
    tagline: "A Great Product Deserves a Great Description — Words That Sell",
    aboutUs: "Creators Touch Global writes product descriptions for e-commerce stores, catalogues, and marketplaces. We have written hundreds of product descriptions for jewellery, skincare, medical devices, and consumer products — each one crafted to convert browsers into buyers.",
    benefits: [
      "Benefit-led product descriptions that sell",
      "SEO-optimised with targeted product keywords",
      "Consistent brand voice across all products",
      "Structured for scannability with bullet points and highlights",
      "Bulk writing for large product catalogues",
      "Category and collection page content",
    ],
    keywords: ["product descriptions", "e-commerce content", "product copywriting", "product page content", "catalogue writing"],
    relatedSlugs: ["fillers-skin"],
  },
  {
    slug: "best-blog-writing-in-vijayawada",
    title: "Blog Writing",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Blog posts that rank on Google and establish your brand as an industry authority.",
    longDesc: "We write blog posts that serve two purposes: ranking on Google for targeted keywords and establishing your brand as a trusted voice in your industry. Every post is researched, structured for SEO, and written in a voice that connects with your audience.",
    tagline: "A Blog That Ranks Is a Business Asset — We Write Posts That Keep Delivering",
    aboutUs: "Creators Touch Global writes blog content for businesses that use content as a long-term growth channel. We have written hundreds of blog posts for healthcare, aesthetics, education, and technology brands — each one designed to attract organic traffic and build authority.",
    benefits: [
      "SEO-targeted blog posts with keyword research",
      "Long-form content for pillar pages and topic clusters",
      "Clear, engaging writing in your brand's voice",
      "Internal linking for improved site architecture",
      "Featured snippet optimisation for position zero",
      "Regular publishing schedule with content calendar",
    ],
    keywords: ["blog writing", "blog content", "SEO blog posts", "blog writing service", "business blog"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-copywriting-in-vijayawada",
    title: "Copywriting",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Persuasive copy that moves people to act — headlines, ads, pages, and beyond.",
    longDesc: "We write copy that converts — ad headlines, landing page copy, email subject lines, CTAs, taglines, and brand messaging. Every word is chosen for impact, tested against alternatives, and refined until it delivers measurable results.",
    tagline: "Words Are the Cheapest and Most Powerful Marketing Tool — We Write the Ones That Work",
    aboutUs: "Creators Touch Global writes conversion-focused copy for ads, landing pages, emails, and brand messaging. Our copywriting is grounded in direct response principles — clear value propositions, compelling hooks, and strong calls to action that move people from interest to action.",
    benefits: [
      "Ad copy for Google, Facebook, and Instagram campaigns",
      "Landing page copy optimised for conversions",
      "Email subject lines and campaign copy",
      "Brand taglines and value proposition development",
      "Website microcopy — buttons, forms, error messages",
      "A/B copy variations for testing",
    ],
    keywords: ["copywriting", "ad copy", "conversion copywriting", "sales copy", "marketing copy"],
    relatedSlugs: ["threadlift", "kensley-aesthetics", "fillers-skin"],
  },
  {
    slug: "best-social-media-content-in-vijayawada",
    title: "Social Media Content",
    category: "Content Writing Services",
    color: "#25D366",
    shortDesc: "Scroll-stopping social media content — captions, scripts, and creative ideas that engage.",
    longDesc: "We create social media content that stops the scroll — compelling captions, Reel scripts, carousel copy, story text, and hashtag strategies. Every piece of content is crafted for the specific platform and audience, designed to drive engagement and build your community.",
    tagline: "Content That Stops the Scroll and Starts the Conversation",
    aboutUs: "Creators Touch Global creates social media content for brands that want to build an engaged following. We write captions that spark conversations, scripts for Reels that get shared, and carousel content that educates and converts — all in your brand's unique voice.",
    benefits: [
      "Platform-specific captions for Instagram, Facebook, LinkedIn",
      "Reel and video scripts with hook-first structure",
      "Carousel and slide content for educational posts",
      "Hashtag research and strategy per post",
      "Content calendar with themed weeks and campaigns",
      "Community engagement responses and comment management",
    ],
    keywords: ["social media content", "Instagram captions", "social media writing", "Reel scripts", "content creation"],
    relatedSlugs: ["kensley-aesthetics", "change-ngo"],
  },

  // ─── AI & Automation ──────────────────────────────────────────────
  {
    slug: "best-ai-chatbot-integration-in-vijayawada",
    title: "AI Chatbot Integration",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "AI chatbots that answer customer queries 24/7 — trained on your business data.",
    longDesc: "We build and integrate AI chatbots that handle customer queries, qualify leads, book appointments, and provide instant support — 24 hours a day, 7 days a week. Each chatbot is trained on your business data to deliver accurate, brand-consistent responses.",
    tagline: "24/7 Customer Support That Never Sleeps — AI Chatbots Trained on Your Business",
    aboutUs: "Creators Touch Global built an AI chatbot for Kensley Aesthetics that handles over 40% of patient queries automatically. We bring the same results-first approach to every chatbot we build — trained on your FAQs, services, and brand voice for responses that feel human.",
    benefits: [
      "Custom AI chatbot trained on your business data",
      "Integration with your website, WhatsApp, or social media",
      "Lead qualification and appointment booking flows",
      "FAQ handling with accurate, brand-consistent responses",
      "Handoff to human agents for complex queries",
      "Analytics dashboard with conversation insights",
    ],
    keywords: ["AI chatbot", "chatbot integration", "customer support chatbot", "AI customer service", "business chatbot"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-whatsapp-business-automation-in-vijayawada",
    title: "WhatsApp Business Automation",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "Automate your WhatsApp Business — responses, reminders, and follow-ups on autopilot.",
    longDesc: "We set up WhatsApp Business API with automated message flows — instant responses, appointment reminders, order confirmations, lead follow-ups, and broadcast campaigns. Your WhatsApp becomes a sales and support channel that runs itself.",
    tagline: "Your WhatsApp Should Work as Hard as Your Best Salesperson — Automation Makes It Happen",
    aboutUs: "Creators Touch Global has automated WhatsApp for clinics handling 200+ daily enquiries, restaurants processing orders, and service businesses following up on leads. Our WhatsApp automation saves hours every day and ensures no enquiry falls through the cracks.",
    benefits: [
      "WhatsApp Business API setup and verification",
      "Automated welcome and quick reply messages",
      "Appointment booking and reminder workflows",
      "Order confirmation and shipping update flows",
      "Lead nurture sequences with timed follow-ups",
      "Broadcast messaging for offers and announcements",
    ],
    keywords: ["WhatsApp Business automation", "WhatsApp API", "WhatsApp bot", "automated WhatsApp", "WhatsApp marketing"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-lead-follow-up-automation-in-vijayawada",
    title: "Lead Follow-up Automation",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "Automated lead follow-ups that convert enquiries into customers — without manual effort.",
    longDesc: "We build automated lead follow-up systems that respond to every enquiry within seconds, send personalised follow-up sequences, and nurture prospects until they are ready to buy. No more leads lost to slow response times or forgotten follow-ups.",
    tagline: "Speed Wins Deals — Automated Follow-ups That Respond in Seconds, Not Hours",
    aboutUs: "Creators Touch Global has built lead follow-up automation for clinics, service businesses, and e-commerce brands. Studies show that responding within 5 minutes increases conversion by 100x — our systems respond in seconds.",
    benefits: [
      "Instant response to new leads via email, WhatsApp, or SMS",
      "Multi-step follow-up sequences over days and weeks",
      "Lead scoring based on engagement and behaviour",
      "CRM integration for pipeline visibility",
      "Personalised messages based on enquiry source and interest",
      "Follow-up analytics with conversion tracking",
    ],
    keywords: ["lead follow-up automation", "automated lead nurturing", "lead management", "follow-up system", "sales automation"],
    relatedSlugs: ["kensley-aesthetics", "meditron-cdc"],
  },
  {
    slug: "best-appointment-reminders-in-vijayawada",
    title: "Appointment Reminders",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "Automated appointment reminders that reduce no-shows and keep your calendar full.",
    longDesc: "We set up automated appointment reminder systems via WhatsApp, SMS, and email that remind your patients or clients about upcoming appointments, allow easy rescheduling, and dramatically reduce no-show rates.",
    tagline: "No-Shows Cost You Money — Automated Reminders Fix That",
    aboutUs: "Creators Touch Global has implemented appointment reminder systems for hospitals, clinics, and service businesses. Our clients report 40-60% reduction in no-shows after implementing automated reminders — that's real revenue recovered.",
    benefits: [
      "Automated reminders via WhatsApp, SMS, and email",
      "Configurable reminder timing — 24 hours, 2 hours, 30 minutes",
      "Easy reschedule and cancellation links in messages",
      "Calendar integration with your booking system",
      "No-show tracking and reporting",
      "Multi-language reminder messages",
    ],
    keywords: ["appointment reminders", "automated reminders", "reduce no-shows", "booking reminders", "SMS reminders"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
  {
    slug: "best-order-confirmation-flows-in-vijayawada",
    title: "Order Confirmation Flows",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "Automated order confirmations, shipping updates, and delivery notifications.",
    longDesc: "We set up automated order confirmation flows that keep your customers informed at every stage — order received, payment confirmed, shipped, out for delivery, and delivered. Every message builds trust and reduces support queries.",
    tagline: "Keep Your Customers in the Loop — Order Updates That Build Trust Automatically",
    aboutUs: "Creators Touch Global builds order notification systems for e-commerce brands and service businesses. Automated order updates reduce support tickets by up to 50% while improving customer satisfaction and repeat purchase rates.",
    benefits: [
      "Order confirmation messages via email and WhatsApp",
      "Payment receipt and invoice generation",
      "Shipping notification with tracking links",
      "Delivery confirmation and feedback request",
      "Return and exchange instruction flows",
      "Integration with Shopify, WooCommerce, or custom platforms",
    ],
    keywords: ["order confirmation", "order updates", "shipping notifications", "e-commerce automation", "order tracking"],
    relatedSlugs: ["fillers-skin"],
  },
  {
    slug: "best-crm-integration-in-vijayawada",
    title: "CRM Integration",
    category: "AI & Automation",
    color: "#c9a227",
    shortDesc: "Connect your tools, unify your data — CRM integration that gives you complete visibility.",
    longDesc: "We integrate CRM systems with your website, WhatsApp, email, and advertising platforms so every lead, enquiry, and customer interaction is captured in one place. Your sales team gets a complete view of every prospect — no more data silos.",
    tagline: "Every Lead in One Place — CRM Integration That Gives Your Sales Team Superpowers",
    aboutUs: "Creators Touch Global sets up and integrates CRM systems for businesses that need to track leads, manage pipelines, and automate follow-ups. We work with HubSpot, Zoho, Salesforce, and custom CRM platforms — connecting them to your website, WhatsApp, and advertising channels.",
    benefits: [
      "CRM setup and configuration for your sales process",
      "Website form integration for automatic lead capture",
      "WhatsApp and email integration for unified communication",
      "Ad platform integration for lead source tracking",
      "Pipeline setup with stages and automation rules",
      "Team training and onboarding support",
    ],
    keywords: ["CRM integration", "CRM setup", "sales CRM", "lead management CRM", "CRM system"],
    relatedSlugs: ["meditron-cdc", "kensley-aesthetics"],
  },
];

export function getIndividualService(slug: string): IndividualService | undefined {
  return INDIVIDUAL_SERVICES.find((s) => s.slug === slug);
}

export function getAllIndividualServiceSlugs(): string[] {
  return INDIVIDUAL_SERVICES.map((s) => s.slug);
}
